/**
 * Local config plugin that patches @react-native-firebase/app to support
 * Swift AppDelegate (generated by RN 0.76+ / Expo 53+).
 *
 * The upstream plugin only handles ObjC/ObjCpp and throws on Swift.
 * This plugin applies the Firebase Google Services plist (the iOS-relevant part)
 * and manually adds `FirebaseApp.configure()` to a Swift AppDelegate.
 *
 * For ObjC/ObjCpp it delegates to the original Firebase plugin as-is.
 */
const { withDangerousMod, withPlugins, IOSConfig } = require('@expo/config-plugins');
const { withIosGoogleServicesFile } = require('@react-native-firebase/app/plugin/build/ios');
const { withBuildscriptDependency, withApplyGoogleServicesPlugin, withCopyAndroidGoogleServices } = require('@react-native-firebase/app/plugin/build/android');
const { modifyObjcAppDelegate } = require('@react-native-firebase/app/plugin/build/ios/appDelegate');
const fs = require('fs');

const SWIFT_FIREBASE_IMPORT = 'import FirebaseCore';
const SWIFT_FIREBASE_CONFIGURE = 'FirebaseApp.configure()';

/**
 * Modifies a Swift AppDelegate to call FirebaseApp.configure() inside
 * application(_:didFinishLaunchingWithOptions:).
 */
function modifySwiftAppDelegate(contents) {
  // Add import if not already present
  if (!contents.includes(SWIFT_FIREBASE_IMPORT)) {
    // Expo SDK 55+ / RN 0.76+: AppDelegate starts with `internal import Expo`
    // (no longer has `import UIKit`). Try both anchors.
    if (contents.includes('internal import Expo')) {
      contents = contents.replace(
        /^(internal import Expo)/m,
        `$1\nimport FirebaseCore`
      );
    } else {
      contents = contents.replace(
        /^(import\s+UIKit)/m,
        `$1\n${SWIFT_FIREBASE_IMPORT}`
      );
    }
  }
  // Add configure call if not already present
  if (!contents.includes(SWIFT_FIREBASE_CONFIGURE)) {
    // Insert after `override func application(` ... `{`
    contents = contents.replace(
      /(override func application\([^)]*didFinishLaunchingWithOptions[^{]*\{)/,
      `$1\n    ${SWIFT_FIREBASE_CONFIGURE}`
    );
    // Fallback: insert after `func application(` ... `{` (non-override variant)
    if (!contents.includes(SWIFT_FIREBASE_CONFIGURE)) {
      contents = contents.replace(
        /(func application\([^)]*didFinishLaunchingWithOptions[^{]*\{)/,
        `$1\n    ${SWIFT_FIREBASE_CONFIGURE}`
      );
    }
  }
  return contents;
}

const withFirebaseSwiftAppDelegate = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const fileInfo = IOSConfig.Paths.getAppDelegate(config.modRequest.projectRoot);
      const { language, path, contents } = fileInfo;

      if (language === 'swift') {
        const newContents = modifySwiftAppDelegate(contents);
        await fs.promises.writeFile(path, newContents);
      } else if (['objc', 'objcpp'].includes(language)) {
        const newContents = modifyObjcAppDelegate(contents);
        await fs.promises.writeFile(path, newContents);
      }
      return config;
    },
  ]);
};

/**
 * Full Firebase app config plugin with Swift AppDelegate support.
 * Use this instead of "@react-native-firebase/app" in app.json plugins.
 */
const withFirebaseApp = (config) => {
  return withPlugins(config, [
    // iOS
    withFirebaseSwiftAppDelegate,
    withIosGoogleServicesFile,
    // Android
    withBuildscriptDependency,
    withApplyGoogleServicesPlugin,
    withCopyAndroidGoogleServices,
  ]);
};

module.exports = withFirebaseApp;
