export const STRINGS = {
  all: 'Todas',
  read: 'Leídas',
  unread: 'Sin Leer',
  follow: 'Seguir',
  following: 'Siguiendo',
  hasStartedToFollow: 'Ha comenzando a seguirte',
  notifications: 'Notificaciones',
  addAMessageToYourMatch: 'Agrega un mensaje a tu partida',
  titleOfYourMatch: 'Titulo de tu partida',
  saveVideo: 'Guardar Video',
  profile: 'Perfil',
  editProfile: 'Editar perfil',
  followers: 'Seguidores',
  record: 'Graba',
  home: 'Home',
  nameAndLastName: 'Nombre y apellido',
  location: 'Ubicación',
  address: 'Dirección',
  description: 'Descripción',
  save: 'Guardar',
  cancel: 'Cancelar',
  discover: 'Descubre',
  clubs: 'Clubes',
  players: 'Siguiendo',
  onLive: 'En vivo',
  latestGames: 'Partidas recientes',
};
